before_script:
  - git config --global user.email "bot@heroku.com"
  - git config --global user.name "Heroku Bot (Travis CI)"

bundler_args: --without development

language: ruby

notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    urls:
      - http://dx-helper.herokuapp.com/travis

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

script: bundle exec rspec -bfs spec
