bundler_args: --without development

language: ruby

notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    urls:
      - http://dx-helper.herokuapp.com/travis

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"

script: bundle exec rspec -bfs spec
